"""Add gmail credentials to User model

Revision ID: 0c18b4bf2d90
Revises: b3484685b835
Create Date: 2025-09-26 05:33:33.633419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c18b4bf2d90'
down_revision = 'b3484685b835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail_credentials_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gmail_credentials_json')

    # ### end Alembic commands ###
