"""Add custom fields functionality

Revision ID: 19a2ce5e5f83
Revises: 761c54ccc1cd
Create Date: 2025-09-26 03:36:54.018419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a2ce5e5f83'
down_revision = '761c54ccc1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field')),
    sa.UniqueConstraint('name', name=op.f('uq_custom_field_name'))
    )
    op.create_table('custom_field_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], name=op.f('fk_custom_field_value_contact_id_contact'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['custom_field.id'], name=op.f('fk_custom_field_value_field_id_custom_field'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_value'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_field_value')
    op.drop_table('custom_field')
    # ### end Alembic commands ###
