"""Add contact types and statuses settings

Revision ID: 342d1852e354
Revises: efca3ab8b979
Create Date: 2025-09-26 01:15:18.968249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342d1852e354'
down_revision = 'efca3ab8b979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_type_id'], ['contact_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])
        batch_op.create_foreign_key(None, 'contact_type', ['contact_type_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')
        batch_op.drop_column('contact_type_id')

    op.drop_table('status')
    op.drop_table('contact_type')
    # ### end Alembic commands ###
