"""Add api_identifier to CustomField

Revision ID: 3fc9ad7bae8a
Revises: e56274925960
Create Date: 2025-09-27 23:49:55.828528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc9ad7bae8a'
down_revision = 'e56274925960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_identifier', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_custom_field_api_identifier'), ['api_identifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_custom_field_api_identifier'), type_='unique')
        batch_op.drop_column('api_identifier')

    # ### end Alembic commands ###
