"""Add timezone to User model

Revision ID: 64c7ea13df4b
Revises: 3fc9ad7bae8a
Create Date: 2025-09-28 05:03:36.624561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c7ea13df4b'
down_revision = '3fc9ad7bae8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # הוסף את העמודה עם ערך ברירת מחדל עבור שורות חדשות, וערך קיים עבור שורות ישנות
        batch_op.add_column(sa.Column('timezone', sa.String(length=100), nullable=False, server_default='Asia/Jerusalem'))

    # לאחר שהעמודה נוספה עם ערך ברירת מחדל, הסר את הגדרת ברירת המחדל ברמת השרת
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('timezone', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###