"""Add activity types and prepare for inline editing

Revision ID: 761c54ccc1cd
Revises: 7ce6f5bfba9e
Create Date: 2025-09-26 02:27:03.957255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761c54ccc1cd'
down_revision = '7ce6f5bfba9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_type')),
    sa.UniqueConstraint('name', name=op.f('uq_activity_type_name'))
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_activity_activity_type_id_activity_type'), 'activity_type', ['activity_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_activity_type_id_activity_type'), type_='foreignkey')
        batch_op.drop_column('activity_type_id')

    op.drop_table('activity_type')
    # ### end Alembic commands ###
