"""Build initial database with all features

Revision ID: 7ce6f5bfba9e
Revises: 
Create Date: 2025-09-26 01:45:38.521740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce6f5bfba9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_type')),
    sa.UniqueConstraint('name', name=op.f('uq_contact_type_name'))
    )
    op.create_table('saved_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_view'))
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_type_id'], ['contact_type.id'], name=op.f('fk_status_contact_type_id_contact_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status'))
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('contact_type_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_type_id'], ['contact_type.id'], name=op.f('fk_contact_contact_type_id_contact_type')),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name=op.f('fk_contact_status_id_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact')),
    sa.UniqueConstraint('email', name=op.f('uq_contact_email'))
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], name=op.f('fk_activity_contact_id_contact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('contact')
    op.drop_table('status')
    op.drop_table('saved_view')
    op.drop_table('contact_type')
    # ### end Alembic commands ###
