"""Add dedicated email fields to Activity model

Revision ID: a4f4d9c4eff4
Revises: 64c7ea13df4b
Create Date: 2025-09-28 05:17:22.934918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f4d9c4eff4'
down_revision = '64c7ea13df4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_body_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_quoted_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('email_quoted_text')
        batch_op.drop_column('email_body_html')
        batch_op.drop_column('email_subject')

    # ### end Alembic commands ###
