"""Add final models for users and custom fields

Revision ID: b3484685b835
Revises: 5a5484e8cf00
Create Date: 2025-09-26 04:27:58.408254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3484685b835'
down_revision = '5a5484e8cf00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.alter_column('field_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.alter_column('field_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
