"""Add gmail_message_id to Activity model

Revision ID: e56274925960
Revises: 0c18b4bf2d90
Create Date: 2025-09-27 23:21:32.863542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56274925960'
down_revision = '0c18b4bf2d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail_message_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_activity_gmail_message_id'), ['gmail_message_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_activity_gmail_message_id'), type_='unique')
        batch_op.drop_column('gmail_message_id')

    # ### end Alembic commands ###
